# ⚠️ Temporariamente desativado porque GitHub Actions ainda não suporta Xcode 16.2
name: Release to TestFlight

on:
    push:
        branches:
            - "main"
            - "release/*"

jobs:
    release:
        runs-on: macos-latest
        
        steps:
            - name: Checkout code
            uses: actions/checkout@v4
            
            - name: Install Fastlane
            run: brew install Fastlane
            
            - name: Install Ruby
            uses: ruby/setup-ruby@v1
            with:
                ruby-version: 3.1
            
            - name: Setup Xcode
            uses: maxim-lobanov/setup-xcode@v1
            with:
                xcode-version: '16.2'
            
            - name: Deploy with Fastlane
            env:
                APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
                APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
                APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
            
            - name: Notificaiton on Notion with sucess
                if: success()
                run: |
                    VERSION="1.0.0"
                    BRANCH="${GITHUB_REF##*/}"
                    DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            
                    curl -X POST https://api.notion.com/v1/pages \
                        -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
                        -H "Content-Type: application/json" \
                        -H "Notion-Version: 2022-06-28" \
                        --data '{
                        "parent": { "database_id": "'"${{ secrets.NOTION_DATABASE_ID }}"'" },
                        "properties": {
                            "Versão": {
                            "title": [
                                {
                                "text": {
                                    "content": "'"$VERSION"'"
                                }
                                }
                            ]
                            },
                            "Data": {
                            "date": {
                                "start": "'"$DATE"'"
                            }
                            },
                            "Branch": {
                            "rich_text": [
                                {
                                "text": {
                                    "content": "'"$BRANCH"'"
                                }
                                }
                            ]
                            },
                            "Estado": {
                            "select": {
                                "name": "✅ Sucesso"
                            }
                            }
                        }
                        }'
                        
          - name: Notificaiton on Notion with error
            if: failure()
            run: |
              BRANCH="${GITHUB_REF##*/}"
              DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

              curl -X POST https://api.notion.com/v1/pages \
                -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
                -H "Content-Type: application/json" \
                -H "Notion-Version: 2022-06-28" \
                --data '{
                  "parent": { "database_id": "'"${{ secrets.NOTION_DATABASE_ID }}"'" },
                  "properties": {
                    "Versão": {
                      "title": [
                        {
                          "text": {
                            "content": "Build Falhada"
                          }
                        }
                      ]
                    },
                    "Data": {
                      "date": {
                        "start": "'"$DATE"'"
                      }
                    },
                    "Branch": {
                      "rich_text": [
                        {
                          "text": {
                            "content": "'"$BRANCH"'"
                          }
                        }
                      ]
                    },
                    "Estado": {
                      "select": {
                        "name": "❌ Falha"
                      }
                    }
                  }
                }'
