name: Release to TestFlight

on:
  push:
    branches:
      - "main"
      - "release/*"

jobs:
  release:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: brew install fastlane

      - name: Setup Xcode (15.2 é o mais recente disponível)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Run Fastlane
        run: fastlane beta
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Telegram notification on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Build enviada com sucesso para o TestFlight!"

      - name: Telegram notification on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ A build falhou. Verifica o erro no GitHub Actions."

      - name: Notion notification on success
        if: success()
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "1.0.0")
          BRANCH="${GITHUB_REF##*/}"
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          curl -X POST https://api.notion.com/v1/pages \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "parent": { "database_id": "'"${{ secrets.NOTION_DATABASE_ID }}"'" },
              "properties": {
                "Versão": { "title": [{"text": {"content": "'"$VERSION"'"}}] },
                "Data": { "date": {"start": "'"$DATE"'" } },
                "Branch": { "rich_text": [{"text": {"content": "'"$BRANCH"'"}}] },
                "Estado": { "select": { "name": "✅ Sucesso" } }
              }
            }'

      - name: Notion notification on failure
        if: failure()
        run: |
          BRANCH="${GITHUB_REF##*/}"
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)

          curl -X POST https://api.notion.com/v1/pages \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "parent": { "database_id": "'"${{ secrets.NOTION_DATABASE_ID }}"'" },
              "properties": {
                "Versão": { "title": [{"text": {"content": "Build Falhada"}}] },
                "Data": { "date": {"start": "'"$DATE"'" } },
                "Branch": { "rich_text": [{"text": {"content": "'"$BRANCH"'"}}] },
                "Estado": { "select": { "name": "❌ Falha" } }
              }
            }'
